mutation createTrade($bookIds: [String], $userId: String) {
  createTrade(bookIds: $bookIds, userId: $userId) {
    trade {
      id
      status
    }
    tradeBooks {
      id
      bookId
    }
  }
}
