query getBooks($where: JSON) {
  ownedBooks(where: $where) {
    id
    title
    author
    publicationYear
    imageUrl
    requestCount
    user {
      id
      screenName
      location
    }
  }
}