scalar JSON
scalar Date
scalar Void

type Mutation {
  createOwnedBook(input: CreateOwnedBookInput): OwnedBook
  updateOwnedBook(id: String, userId: String): OwnedBook
  deleteOwnedBook(id: String!): String
  createTrade(bookId: String, userId: String): Trade
  deleteTrade(bookId: String!, userId: String!): Trade
  createUser(id: String, fullName: String, location: String): User
  updateUser(id: String, fullName: String, location: String): User
}

input CreateOwnedBookInput {
  id: String
  userId: String
  title: String
  author: String
  imageUrl: String
  publicationYear: Int
  available: Boolean
}

type OwnedBook {
  id: String!
  userId: String
  trades(
    limit: Int
    order: String
    where: JSON
    offset: Int
  ): [Trade]
  user: User
  title: String
  author: String
  imageUrl: String
  publicationYear: Int
  available: Boolean
}

type Query {
  ownedBooks(
    limit: Int
    order: String
    where: JSON
    offset: Int
  ): [OwnedBook]

  ownedBook(
    id: String
  ): OwnedBook

  trades(
    limit: Int
    order: String
    where: JSON
    offset: Int
  ): [Trade]

  trade(
    bookId: String
    userId: String
  ): Trade

  users(
    limit: Int
    order: String
    where: JSON
    offset: Int
  ): [User]

  user(
    id: String
  ): User

  goodreads(
    q: String
    field: String
  ): [Book]
}

type Book {
  id: String
  title: String
  author: String
  imageUrl: String
  publicationYear: Int
  owned: Boolean
}

type Trade {
  id: String!
  bookId: String
  status: Int
  ownedBook: OwnedBook
}

type TradeBooks {
  tradeId: String!
  bookId: String!
}

type User {
  id: String!
  fullName: String
  location: String
  screenName: String
  email: String
  ownedBooks(
    limit: Int
    order: String
    where: JSON
    offset: Int
  ): [OwnedBook]
}
