/* eslint-disable react/jsx-filename-extension */
import Head from 'next/head';
import Layout from '../lib/components/Layout';
import HeroImage from '../lib/components/HeroImage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Swap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HeroImage src="images/books-hero.jpg" />
        <small className="float-right"><a href="https://www.freepik.com/free-photo/books-randomly-stacked-on-shelf_2543726.htm">Images provided by Freepik</a></small>
      </Layout>
    </>
  );
}
