query getBooks($where: JSON) {
  ownedBooks(where: $where) {
    id
    bookId
    title
    author
    publicationYear
    imageUrl
    requestCount
    user {
      id
      name
      location
    }
  }
}
