query getRequests {
  trades {
    id
    userId
    status
    createdAt
    updatedAt
    tradeBooks {
      id
      ownedBook {
        id
        title
        author
        publicationYear
        imageUrl
        user {
          id
          name
          location
        }
      }
    }
  }
}
